source "http://rubygems.org"

gem "nats", '>= 0.4.8'
gem "datamapper", "~> 1.2.0"
gem "do_sqlite3"
gem "dm-sqlite-adapter"
gem "eventmachine"
gem "em-http-request"
gem "escape_utils", '0.3.2'
gem "json"
gem "pg"
gem "uuidtools"
gem "ruby-hmac", :require => "hmac-sha1"
gem "thin"
gem "sinatra"
gem "logging"

gem 'vcap_common', path: '../../common', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', :require => ['vcap/logging']

group :test do
  gem "rake"
  gem "rspec"
  gem 'simplecov', '~> 0.8.2'
  gem "ci_reporter"
end

