source "http://rubygems.org"

gem "nats", '>= 0.4.26'
gem "datamapper", ">= 0.10.2"
gem "do_sqlite3", :require => nil
gem "eventmachine", '~> 0.12.11.cloudfoundry.3'
gem "eventmachine_httpserver", :require => "evma_httpserver"
gem "json"
gem "uuidtools"
gem "ruby-hmac", :require => "hmac-sha1"
gem "em-http-request"
gem "sinatra"
gem "thin"
gem "logging"

gem 'vcap_common', path: '../../common', :require => ['vcap/common', 'vcap/component']

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov"
  gem "ci_reporter"
end
